### ISSUE TITLE
Automatic conversion of stats from numeric to integer is causing loss of data

### ISSUE THREAD

**Issue by jkope892** [PatrickChodowski/NBAr#3]
Amazing package.  But I noticed the package automatically converts numbers to integers dropping the decimal points, which is making working with averages sort of tricky and also causing many variables (ex PIE and Freq) to appear as 0, especially with single digit percentages.  For example, team shotclock FG Freq is 4%, but stored as 0.04 in the raw data is converting it to 0.

**Comment by PatrickChodowski** [comment]
Hello, 

Thank you for your feedback! I will have a look

**Comment by PatrickChodowski** [comment]
Version 2.1.2 should fix the problem

**Comment by peteowen1** [comment]
> Version 2.1.2 should fix the problem

Version 2.1.2 hasn't fixed the problem. 
The problem seems to be when you use:

mutate_at(vars(- matches('_pct|spd|dist|_frequency|pie|per|_freq|_rating')), c_to_int)

the c_to_int function converts all these to an integer so a frequency of 0.04 gets converted to 0.

I don't get why c_to_int is needed at all?? 
Why do you need to convert numerics to integers can't we just leave them as numeric?

p.s. just recently stumbled upon the package and love your work, couldn't find a good scraper elsewhere and this package does everything I was looking for. Hoping by commenting I can contribute to it in someway!

**Comment by PatrickChodowski** [comment]
Hi, thanks for the feedback

originally with c_to_int I wanted to convert ID-like columns to integers (player_id, game_id, etc.) from floats

let me have a look again at it

**Comment by peteowen1** [comment]
Someone just opened up an issue with the same problem hahah

https://github.com/PatrickChodowski/NBAr/issues/6

I think I would just specify the ID columns to be integers and let all the other columns be numeric unless there's a good reason not to I suppose. 
Especially since the default is per-game numbers which in general are always going to be a decimal therefore converting to integer will cause a loss of information.

**Comment by PatrickChodowski** [comment]
Hi, I removed the conversion to int completely, hopefully this helps and doesnt break anything
